version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile  # Dockerfile avec extensions Laravel
    container_name: conic-chantier
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  node:
    image: node:18
    container_name: laravel-node
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

  adminer:
    image: adminer
    container_name: laravel-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge
