services:
  # PHP + Composer
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile  # Optionnel (si extensions PHP personnalisées)
    image: php:8.0.30-fpm  # Remplace toute la section build:
    container_name: conic-chantier
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - default  # Utilise le réseau bridge par défaut
      - laravel-network
  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  # Node.js (pour Vite/Mix)
  node:
    image: node:18
    container_name: laravel-node
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel-network

networks:
  laravel-network:
    name: laravel-network
    driver: bridge
